name: ci

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: docker setup
        uses: docker/setup-buildx-action@v3

      - name: backend lint
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          tags: full-stack-backend:latest
          push: false

      - name: frontend lint
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: full-stack-frontend:latest
          push: false 